function controle()
{
if (gemengdoef.oef01.value == "F")  gemengdoef.opl01.src = "../images/goed.gif"
else gemengdoef.opl01.src = "../images/fout.gif"
if (gemengdoef.oef02.value == "P")  gemengdoef.opl02.src = "../images/goed.gif"
else gemengdoef.opl02.src = "../images/fout.gif"
if (gemengdoef.oef03.value == "K")  gemengdoef.opl03.src = "../images/goed.gif"
else gemengdoef.opl03.src = "../images/fout.gif"
if ((gemengdoef.oef04.value == "[MG]") || (gemengdoef.oef04.value == "[GM]")) gemengdoef.opl04.src = "../images/goed.gif"
else gemengdoef.opl04.src = "../images/fout.gif"
if ((gemengdoef.oef05.value == "[MN]") || (gemengdoef.oef05.value == "[NM]"))  gemengdoef.opl05.src = "../images/goed.gif"
else gemengdoef.opl05.src = "../images/fout.gif"
if ((gemengdoef.oef06.value == "[DK]") || (gemengdoef.oef06.value == "[KD]"))  gemengdoef.opl06.src = "../images/goed.gif"
else gemengdoef.opl06.src = "../images/fout.gif"
if (gemengdoef.oef07.value == "I")  gemengdoef.opl07.src = "../images/goed.gif"
else gemengdoef.opl07.src = "../images/fout.gif"
if (gemengdoef.oef08.value == "G")  gemengdoef.opl08.src = "../images/goed.gif"
else gemengdoef.opl08.src = "../images/fout.gif"
if ((gemengdoef.oef09.value == "[GH]") || (gemengdoef.oef09.value == "[HG]"))  gemengdoef.opl09.src = "../images/goed.gif"
else gemengdoef.opl09.src = "../images/fout.gif"
if ((gemengdoef.oef10.value == "[LQ]") || (gemengdoef.oef10.value == "[QL]"))  gemengdoef.opl10.src = "../images/goed.gif"
else gemengdoef.opl10.src = "../images/fout.gif"
if (gemengdoef.oef11.value == "M")  gemengdoef.opl11.src = "../images/goed.gif"
else gemengdoef.opl11.src = "../images/fout.gif"
if (gemengdoef.oef12.value == "N")  gemengdoef.opl12.src = "../images/goed.gif"
else gemengdoef.opl12.src = "../images/fout.gif"
if (gemengdoef.oef13.value == "H")  gemengdoef.opl13.src = "../images/goed.gif"
else gemengdoef.opl13.src = "../images/fout.gif"
if ((gemengdoef.oef14.value == "[HL]") || (gemengdoef.oef14.value == "[LH]")) gemengdoef.opl14.src = "../images/goed.gif"
else gemengdoef.opl14.src = "../images/fout.gif"
if ((gemengdoef.oef15.value == "[KQ]") || (gemengdoef.oef15.value == "[QK]"))  gemengdoef.opl15.src = "../images/goed.gif"
else gemengdoef.opl15.src = "../images/fout.gif"
if ((gemengdoef.oef16.value == "[IG]") || (gemengdoef.oef16.value == "[GI]"))  gemengdoef.opl16.src = "../images/goed.gif"
else gemengdoef.opl16.src = "../images/fout.gif"
if (gemengdoef.oef17.value == "K")  gemengdoef.opl17.src = "../images/goed.gif"
else gemengdoef.opl17.src = "../images/fout.gif"
if (gemengdoef.oef18.value == "D")  gemengdoef.opl18.src = "../images/goed.gif"
else gemengdoef.opl18.src = "../images/fout.gif"
if ((gemengdoef.oef19.value == "[FG]") || (gemengdoef.oef19.value == "[GF]"))  gemengdoef.opl19.src = "../images/goed.gif"
else gemengdoef.opl19.src = "../images/fout.gif"
if ((gemengdoef.oef20.value == "[CO]") || (gemengdoef.oef20.value == "[OC]"))  gemengdoef.opl20.src = "../images/goed.gif"
else gemengdoef.opl20.src = "../images/fout.gif"
}

